update some issues

diff --git a/hotfix b/hotfix
--- a/hotfix
+++ b/hotfix
@@ -1,4 +1,14 @@
 #!/bin/sh
+if [ $# != 0 ];then
+	echo "fatal: usage( hotfix ) no args"
+	exit 1
+fi
+
+if [ ! -e alps ];then
+	echo "Error exec path!!!"
+	exit 1
+fi
+
 echo "------->begin"
 
 root=$PWD
diff --git a/pack b/pack
--- a/pack
+++ b/pack
@@ -4,6 +4,11 @@ if [ $# != 2 ];then
 	exit 1
 fi
 
+if [ ! -e alps ];then
+	echo "Error exec path!!!"
+	exit 1
+fi
+
 if [ ! -e alps/out ];then
 	echo "No out dir!!!"
 	exit 1
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,8 +1,15 @@
 #!/bin/sh
 if [ $# != 1 ];then
-	echo "fatal: usage( ./update mr12|md77|mq89 )"
+	echo "fatal: usage( update mr12|md77|mq89|mc12 )"
 	exit 1
 fi
+
+if [ ! -e alps ];then
+	echo "Error exec path!!!"
+	exit 1
+fi
+
+
 echo "------->begin update code"
 
 cd alps/system/vold/
